-- Add all missing columns to site_settings table
ALTER TABLE site_settings 
ADD COLUMN IF NOT EXISTS show_hero BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS hero_border_radius INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS hero_overlay_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS hero_overlay_color TEXT DEFAULT '#000000',
ADD COLUMN IF NOT EXISTS hero_overlay_opacity DECIMAL(3,2) DEFAULT 0.3,
ADD COLUMN IF NOT EXISTS hero_height INTEGER DEFAULT 400,
ADD COLUMN IF NOT EXISTS homepage_product_limit INTEGER DEFAULT 8,
ADD COLUMN IF NOT EXISTS product_grid_columns INTEGER DEFAULT 4,
ADD COLUMN IF NOT EXISTS product_card_style TEXT DEFAULT 'minimal',
ADD COLUMN IF NOT EXISTS price_badge_color TEXT DEFAULT '#3b82f6',
ADD COLUMN IF NOT EXISTS footer_text_size INTEGER DEFAULT 14,
ADD COLUMN IF NOT EXISTS footer_logo_size INTEGER DEFAULT 32,
ADD COLUMN IF NOT EXISTS footer_show_border BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS footer_show_logo BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS footer_title_size INTEGER DEFAULT 24,
ADD COLUMN IF NOT EXISTS footer_title_weight INTEGER DEFAULT 600,
ADD COLUMN IF NOT EXISTS footer_title_font TEXT DEFAULT 'inherit',
ADD COLUMN IF NOT EXISTS footer_title_line_height DECIMAL(3,2) DEFAULT 1.2,
ADD COLUMN IF NOT EXISTS footer_symbol TEXT DEFAULT '™',
ADD COLUMN IF NOT EXISTS hero_button_text TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS hero_button_link TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS hero_title_font TEXT DEFAULT 'inherit',
ADD COLUMN IF NOT EXISTS hero_title_size INTEGER DEFAULT 48,
ADD COLUMN IF NOT EXISTS product_zoom_type TEXT DEFAULT 'simple',
ADD COLUMN IF NOT EXISTS product_page_layout TEXT DEFAULT 'default',
ADD COLUMN IF NOT EXISTS add_to_cart_button_text TEXT DEFAULT 'Add to Cart',
ADD COLUMN IF NOT EXISTS product_card_height TEXT DEFAULT 'square',
ADD COLUMN IF NOT EXISTS payment_paypal_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS payment_kpay_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS payment_momo_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS momo_number TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS momo_name TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS momo_instructions TEXT DEFAULT 'Scan the QR code or tap to dial, then enter your transaction ID.',
ADD COLUMN IF NOT EXISTS momo_dial_code TEXT DEFAULT '+250';

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
